theme: jekyll-theme-cayman
title: Secure Archtecture Lab., GSAI, U-Hyogo
timezone: Asia/Tokyo
url: "https://secarchlab.github.io"
baseurl: ""
github:
  is_project_page: false
show_downloads: false
google_analytics: UA-163123480-1
